version: "3"
services:
  node:
    build:
      context: .
      dockerfile: node.docker
      args:
        privatekey: df504d175ae63abf209bad9dda965310d99559620550e74521a6798a41215f46
        password: word
        bootnode: enode://b816dd9a04d9b95cf52d060ccc243c6f84dbca4aa79bc2da85d108a1387f8f013ac1311697a7b60181d282891bbf42a7dfc0b23f4687eee8a3825187e3e44ef4@35.238.28.246?discport=30301
    environment:
      - address=0x8cc5a1a0802db41db826c2fcb72423744338dcb0
    volumes:
      - storage:/opt/storage
    ports:
      - 30307:30307
      - 7545:7545 
      - 8546:8546
  main_net:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    volumes:
      - ./ganache_data:/ganache_data
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
      - --networkId
      - '5555'
      - --hostname
      - '0.0.0.0'
      - --debug
  # api:
  #   build:
  #     context: .
  #     dockerfile: api.docker
  #   ports:
  #     - 3001:3001
  #   depends_on:
  #     - node
  #     - main_net
volumes:
  storage: