version: "3"
services:
  stoa-billing-postgres:
    image: postgres:12.2-alpine
    volumes:
      - stoa-billing-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - stoa-network-billing
    ports:
      - ${POSTGRES_PORT}:5432
  stoa-billing-pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - stoa-network-billing
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - stoa-billing-postgres
  stoa-billing-main-net:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    volumes:
      - ./ganache_data:/ganache_data
    networks:
      - stoa-network-billing
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --networkId
      - '5555'
      - -e
      - '10000'
  stoa-billing-api:
    build:
      context: .
      dockerfile: api.docker
    dns:
      - 8.8.8.8
      - 4.4.4.4
    ports:
      - 3001:3001
    networks:
      - stoa-network-billing
    depends_on:
      - stoa-billing-main-net
      - stoa-billing-postgres
volumes:
  stoa-billing-postgres:
networks:
  stoa-network-billing:
    external: true
