version: "3"
services:
  main_net:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    volumes:
      - ./ganache_data:/ganache_data
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --networkId
      - '5555'
      - -e
      - '10000'
  api:
    build:
      context: .
      dockerfile: api.docker
    dns:
      - 8.8.8.8
      - 4.4.4.4
    ports:
      - 3001:3001
    depends_on:
      - main_net