version: "3"
services:
  node:
    build:
      context: .
      dockerfile: node.docker
      args:
        privatekey: df504d175ae63abf209bad9dda965310d99559620550e74521a6798a41215f46
        password: word
        bootnode: enode://f3e4d75df33d46fb5feacdb36a14fe3ca50e07fcb12ec3e2b7164b54015cb58a7f87210be8026c3c8f374340a2186a1d515dbd12ef08b5e3e0ef13deb47602b1@192.168.8.156:30301
    environment:
      - address=0x8cc5a1a0802db41db826c2fcb72423744338dcb0
    volumes:
      - storage:/opt/storage
    ports:
      - 30307:30307
      - 7545:7545 
      - 8546:8546
  main_net:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    volumes:
      - ./ganache_data:/ganache_data
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --networkId
      - '5555'
  api:
    build:
      context: .
      dockerfile: api.docker
    volumes:
      - .:/usr/src/app
    ports:
      - 3001:3001
    depends_on:
      - node
      - main_net
    command: ["./wait-for-it.sh", "-t", "60", "node:7545", "--", "npm", "run", "start:prod"]
volumes:
  storage: